# Generated by Django 4.1.1 on 2022-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_rating_product_featured_product_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True),
        ),
    ]
